# Generated by Django 3.2.25 on 2024-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('brand', models.CharField(help_text='The brand of the product.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='The number of items available in stock.')),
                ('category', models.CharField(choices=[('SH', 'Shirts'), ('TS', 'T-Shirts/shirts'), ('cr', 'carpener-pants/cargos'), ('js', 'jeans'), ('JK', 'Jackets'), ('rj', 'racing-Jackets'), ('wd', 'windbreaker'), ('jt', 'jorts'), ('as', 'accesories'), ('sh', 'shoes'), ('hd', 'hoodies/sweat-shirts')], help_text='The category of the product.', max_length=2)),
                ('size', models.CharField(blank=True, help_text='The size of the product (e.g., S, M, L, XL).', max_length=50)),
                ('color', models.CharField(blank=True, help_text='The color of the product.', max_length=50)),
                ('material', models.CharField(blank=True, help_text='The material of the product.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the product was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the product was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the product is active and available for sale.')),
                ('image', models.ImageField(blank=True, help_text='An image of the product.', null=True, upload_to='products/')),
            ],
        ),
    ]
