# Generated by Django 3.2.25 on 2025-01-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20250104_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categories',
        ),
    ]
