# Generated by Django 3.2.25 on 2025-01-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_category_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
